pipeline {
    
    agent any
    stages {
    
        stage('Checkout') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: params.BRANCH.trim()]], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[url: params.GIT_URL.trim()]]])
            }
        }

        stage('Setup') {
            steps {
                script {
                    //Generate a packaged version, this version is associated with the git branch name, git commit id, and the version generation date should be marked at the same time
                    env.GIT_COMMIT = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                    env.GIT_COMMIT_SHORT = sh(script: "git log -1 --pretty=format:%h", returnStdout: true).trim()
                    env.VERSION = "master" + "-" +env.BUILD_NUMBER + "-" + env.GIT_COMMIT_SHORT

                }
            }
        }
        stage('build code') {
            steps {
                script {
                   sh "pwd"
                    
                   if ("${env.Language}" == "NodeJS") {
                        //sh npm install  //The server where the jenkins server is located requires npm to be installed.
                       echo "${env.Language}"
                    } else if ("${env.Language}" == "Java") {
                        //sh "mvn/ant install command"  //The server where the jenkins server is located requires maven/ant to be installed.
                       echo "${env.Language}"
                    }
                }
            }
        }    
        stage('build image') {
            steps {
                script {
                    //Get hrb credentials id.
                    //withCredentials([Skipdetection(credentialsId: 'hrb', xxVariable: 'xx', xxVariable: 'xx')]) {           
                        //sh "docker login -u ${xx} -p ${xx} hrb"
                        sh "docker build -t product/${env.ServiceName}:${env.VERSION} ." //Use the version number generated by the setup step to name the tag of docker image.
                        //sh "docker tag xxx/${env.ServiceName}:${env.VERSION} hrb/xxx/${env.ServiceName}:${env.VERSION}"
                        //sh "docker push hrb/xxx/xxx:${env.VERSION}"
                    echo "${env.ServiceName}"
                    //}
                }
            }
        }
        
        stage("Set Build Description"){
            steps {
                script {
                    currentBuild.displayName = "${env.VERSION}"
                    currentBuild.description = "hrb/xxx/${env.ServiceName}:${env.VERSION}"
                }
            }
        }

    }
    post {
        success {
            echo 'I succeeded!'
        }
        unstable {
            echo 'I am unstable :/'
        }
        failure {
            echo 'I failed :('
        }
        changed {
            echo 'Things are different...'
        }
    }
}
